version: '3.3'

services:
  traefik:
    restart: always
    container_name: traefik
    image: traefik:v2.2
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./etc:/etc/traefik/
      - ./logs:/var/log/traefik